name: elder_launcher
description: A launcher focused on simplicity and legibility.
publish_to: 'none'
version: 1.5+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0  
  contacts_service: ^0.6.3
  device_apps: ^2.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  permission_handler: ^8.3.0
  provider: ^6.0.2
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
