name: elder_launcher
description: A launcher focused on simplicity and legibility.

version: 1.1+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  auto_size_text: ^2.1.0
  contacts_service: ^0.4.6
  device_apps: ^1.1.0
  intl: ^0.16.1
  pedantic: ^1.9.0
  permission_handler: ^5.0.1+1
  provider: ^4.3.1
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
