name: elder_launcher
description: A launcher focused on simplicity and legibility.
publish_to: 'none'
version: 1.3+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:  
  auto_size_text: ^2.1.0  
  contacts_service: ^0.3.10
  device_apps: ^2.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  permission_handler: ^6.1.1
  provider: ^5.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  effective_dart: ^1.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
